package com.start.CityVibe.domain.evento;

public enum TipoEvento {
    SHOW,
    FESTIVAL_MUSICA_VIVA,
    SHOW_DJS,
    FESTIVAL_MUSICA_ELETRONICA,
    SHOW_STANDUP,
    CONCERTO_ROCK,
    FESTIVAL_CULTURA_POP,
    EVENTO_GOSPEL,
    ENCONTRO_INFLUENCIADORES,
    FESTIVAL_CINEMA_INDEPENDENTE,
    FEIRA_MODA_ESTILO,
    WORKSHOP_FOTOGRAFIA_VIDEO,
    FESTIVAL_GASTRONOMIA,
    MARATONA_E_SPORTS,
    RALLY_AVENTURA_AR_LIVRE,
    EXPOSICAO_ARTE_CONTEMPORANEA,
    PALESTRA_CARREIRA_EMPREENDENDO,
    ENCONTRO_TECH_STARTUPS,
    FESTIVAL_CULTURA_URBANA,
    FESTIVAL_MUSICA_INDIE,
    KARAOKE_AO_VIVO
}
